In [2]:
import numpy as np
import pandas as pd
import csv

In [4]:
df_category_attr_combined_from_imgfile = pd.read_csv('./csv/attr_category_combined_asdf.csv')

In [5]:
df_category_attr_combined_from_imgfile.head()

,image_name,category_name,category_label,a-line,abstract,abstract chevron,abstract chevron print,abstract diamond,abstract floral,abstract floral print,...,zeppelin,zig,zigzag,zip,zip-front,zip-pocket,zip-up,zipped,zipper,zippered
0,1981_Graphic_Ringer_Tee_img_00000001,shirt,0,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
1,1981_Graphic_Ringer_Tee_img_00000002,shirt,0,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
2,1981_Graphic_Ringer_Tee_img_00000003,shirt,0,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
3,1981_Graphic_Ringer_Tee_img_00000004,shirt,0,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4,1981_Graphic_Ringer_Tee_img_00000005,shirt,0,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [6]:
df_attr_chosen = pd.read_csv('./csv/name_merged.csv')

In [7]:
df_attr_chosen.head()

,image_name,category_name,category_label,short sleeves,red,pink,summer,others,striped,floral,dotted,checker,no sleeves,long sleeves,short,long,woman,winter
0,1981_Graphic_Ringer_Tee_img_00000001,shirt,0,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
1,1981_Graphic_Ringer_Tee_img_00000002,shirt,0,-1,-1,-1,-1,1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1
2,1981_Graphic_Ringer_Tee_img_00000003,shirt,0,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1
3,1981_Graphic_Ringer_Tee_img_00000004,shirt,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4,1981_Graphic_Ringer_Tee_img_00000005,shirt,0,-1,-1,-1,-1,1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1

In [8]:
attr_frequency = (df_attr_chosen.iloc[:,1:] == 1).sum(axis=0)
attr_frequency_sort=attr_frequency.sort_values(ascending = False)

In [9]:
attr_frequency_sort

woman             71018
others            34890
no sleeves        24226
long              21066
floral            17513
striped           12970
long sleeves       5931
summer             4875
red                4726
pink               4448
short              3607
dotted             3109
winter             1266
checker            1150
category_label      524
short sleeves        67
category_name         0
dtype: int64