In [1]:
import pandas as pd
import csv

In [4]:
df_category_combined = pd.read_csv('../attr_category_combined_asdf.csv')

In [5]:
df_category_combined.head()

,image_name,category_name,category_label,a-line,abstract,abstract chevron,abstract chevron print,abstract diamond,abstract floral,abstract floral print,...,zeppelin,zig,zigzag,zip,zip-front,zip-pocket,zip-up,zipped,zipper,zippered
0,1981_Graphic_Ringer_Tee_img_00000001,shirt,0,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
1,1981_Graphic_Ringer_Tee_img_00000002,shirt,0,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
2,1981_Graphic_Ringer_Tee_img_00000003,shirt,0,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
3,1981_Graphic_Ringer_Tee_img_00000004,shirt,0,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4,1981_Graphic_Ringer_Tee_img_00000005,shirt,0,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1